/*
 * The MIT License
 *
 * Copyright 2019 lucamazza.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package snowpackage;

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Starting page of the application.
 * 
 * @author Luca Mazza
 * @since 1.0
 */
public class SnowFlake extends javax.swing.JDialog {

    /**
     * Creates new form OpenNew
     */
    public SnowFlake(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
    }
    
    public void browse(String url){
        try{
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }catch(IOException e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        NewFlake = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        OpenFlake = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 255));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setSize(new java.awt.Dimension(600, 350));

        controlPanel.setAlignmentX(1.0F);
        controlPanel.setAlignmentY(1.0F);
        controlPanel.setLayout(new java.awt.GridBagLayout());

        NewFlake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snowflake/img/iu copy.png"))); // NOI18N
        NewFlake.setMaximumSize(new java.awt.Dimension(75, 75));
        NewFlake.setMinimumSize(new java.awt.Dimension(75, 75));
        NewFlake.setPreferredSize(new java.awt.Dimension(75, 75));
        NewFlake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFlakeActionPerformed(evt);
            }
        });
        controlPanel.add(NewFlake, new java.awt.GridBagConstraints());

        jLabel2.setText("      ");
        controlPanel.add(jLabel2, new java.awt.GridBagConstraints());

        OpenFlake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snowflake/img/iu.png"))); // NOI18N
        OpenFlake.setMaximumSize(new java.awt.Dimension(75, 75));
        OpenFlake.setMinimumSize(new java.awt.Dimension(75, 75));
        OpenFlake.setPreferredSize(new java.awt.Dimension(75, 75));
        OpenFlake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFlakeActionPerformed(evt);
            }
        });
        controlPanel.add(OpenFlake, new java.awt.GridBagConstraints());

        getContentPane().add(controlPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("© Luca Mazza");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snowflake/img/if.png"))); // NOI18N
        jLabel3.setText("lucamazzzza");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snowflake/img/iu copy 2.png"))); // NOI18N
        jLabel4.setText("MazzaLuca");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snowflake/img/isdfa.png"))); // NOI18N
        jLabel5.setText("samtinfo.ch");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(12, 12, 12))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Creates a new MainFrame instance.
     * 
     * @param evt <code>ActionEvent</code> event.
     */
    private void NewFlakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFlakeActionPerformed
        this.dispose();
        MainFrame sfp = new MainFrame(false, "");
        sfp.setVisible(true);
    }//GEN-LAST:event_NewFlakeActionPerformed
    /**
     * Loads an existing snowflake.
     * 
     * @param evt <code>ActionEvent</code> event.
     */
    private void OpenFlakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFlakeActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter fnf = new FileNameExtensionFilter("Snowflake file (*.snowflake)", "snowflake");
        jfc.setFileFilter(fnf);
        jfc.showDialog(this, "Open");
        try{
            String handle = new String(jfc.getSelectedFile().toString());
            MainFrame sfp = new MainFrame(true, handle);
            this.dispose();
            sfp.setVisible(true);
        }catch(NullPointerException npe){
            System.out.println("Closed");
        }
    }//GEN-LAST:event_OpenFlakeActionPerformed
    /**
     * Instagram link.
     * 
     * @param evt <code>ActionEvent</code> event.
     */
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        browse("https://instagram.com/lucamazzzza");
    }//GEN-LAST:event_jLabel3MouseClicked
    /**
     * Github link.
     * 
     * @param evt <code>ActionEvent</code> event.
     */
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        browse("https://github.com/MazzaLuca");
    }//GEN-LAST:event_jLabel4MouseClicked
    /**
     * Personal website link.
     * 
     * @param evt <code>ActionEvent</code> event.
     */
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        browse("http://samtinfo.ch/i17mazluc");
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * Main method.
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnowFlake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SnowFlake dialog = new SnowFlake(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewFlake;
    private javax.swing.JButton OpenFlake;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
