/*
 * The MIT License
 *
 * Copyright 2019 lucamazza.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package snowflake;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author lucamazza
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        showLine = new javax.swing.JToggleButton();
        pickTriangleColor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        generateSnowFlake = new javax.swing.JButton();
        snowFlakePanel = new snowflake.SnowFlakePanel();
        menuBar = new javax.swing.JMenuBar();
        SaveAs = new javax.swing.JMenu();
        SaveAsPng = new javax.swing.JMenuItem();
        SaveAsSvg = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Reset = new javax.swing.JMenuItem();
        Undo = new javax.swing.JMenuItem();
        Redo = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        Preview = new javax.swing.JMenuItem();
        showLines = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        showLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snowflake/img/PolygonIcon.png"))); // NOI18N
        showLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLineActionPerformed(evt);
            }
        });
        jPanel2.add(showLine);

        pickTriangleColor.setText("Color");
        pickTriangleColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickTriangleColorActionPerformed(evt);
            }
        });
        jPanel2.add(pickTriangleColor);
        jPanel2.add(jSeparator2);

        jButton2.setText("jButton2");
        jPanel2.add(jButton2);

        jButton3.setText("jButton3");
        jButton3.setMaximumSize(new java.awt.Dimension(70, 70));
        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        generateSnowFlake.setText("Generate");
        generateSnowFlake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSnowFlakeActionPerformed(evt);
            }
        });
        jPanel1.add(generateSnowFlake);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout snowFlakePanelLayout = new javax.swing.GroupLayout(snowFlakePanel);
        snowFlakePanel.setLayout(snowFlakePanelLayout);
        snowFlakePanelLayout.setHorizontalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        snowFlakePanelLayout.setVerticalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        getContentPane().add(snowFlakePanel, java.awt.BorderLayout.CENTER);

        SaveAs.setText("Save as");

        SaveAsPng.setText("PNG");
        SaveAsPng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsPngActionPerformed(evt);
            }
        });
        SaveAs.add(SaveAsPng);

        SaveAsSvg.setText("SVG");
        SaveAsSvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsSvgActionPerformed(evt);
            }
        });
        SaveAs.add(SaveAsSvg);

        menuBar.add(SaveAs);

        Edit.setText("Edit");

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        Edit.add(Reset);

        Undo.setText("Undo");
        Undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoActionPerformed(evt);
            }
        });
        Edit.add(Undo);

        Redo.setText("Redo");
        Redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedoActionPerformed(evt);
            }
        });
        Edit.add(Redo);

        menuBar.add(Edit);

        View.setText("View");

        Preview.setText("Preview");
        Preview.setMinimumSize(new java.awt.Dimension(1280, 720));
        Preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewActionPerformed(evt);
            }
        });
        View.add(Preview);

        showLines.setSelected(true);
        showLines.setText("Show lines");
        showLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLinesActionPerformed(evt);
            }
        });
        View.add(showLines);

        menuBar.add(View);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveAsPngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsPngActionPerformed
        // Save as PNG
    }//GEN-LAST:event_SaveAsPngActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        snowFlakePanel.poly.reset();
        snowFlakePanel.points.clear();
        snowFlakePanel.repaint();
    }//GEN-LAST:event_ResetActionPerformed

    private void SaveAsSvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsSvgActionPerformed
        // Save as SVG
    }//GEN-LAST:event_SaveAsSvgActionPerformed

    private void UndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoActionPerformed
        // Undo
    }//GEN-LAST:event_UndoActionPerformed

    private void RedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedoActionPerformed
        // Redo
    }//GEN-LAST:event_RedoActionPerformed

    private void PreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewActionPerformed
        // preview
    }//GEN-LAST:event_PreviewActionPerformed

    private void showLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLinesActionPerformed

    }//GEN-LAST:event_showLinesActionPerformed

    private void generateSnowFlakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSnowFlakeActionPerformed
        snowFlakePanel.generated = !snowFlakePanel.generated;
        snowFlakePanel.repaint();
    }//GEN-LAST:event_generateSnowFlakeActionPerformed

    private void pickTriangleColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickTriangleColorActionPerformed
        JColorChooser jcc = new JColorChooser();
        Color c = jcc.showDialog(null, "Select a color", Color.BLACK);
        snowFlakePanel.triangleColor = c;
        snowFlakePanel.repaint();
    }//GEN-LAST:event_pickTriangleColorActionPerformed

    private void showLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLineActionPerformed
        snowFlakePanel.showLines = !snowFlakePanel.showLines;
        snowFlakePanel.repaint();
    }//GEN-LAST:event_showLineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Preview;
    private javax.swing.JMenuItem Redo;
    private javax.swing.JMenuItem Reset;
    private javax.swing.JMenu SaveAs;
    private javax.swing.JMenuItem SaveAsPng;
    private javax.swing.JMenuItem SaveAsSvg;
    private javax.swing.JMenuItem Undo;
    private javax.swing.JMenu View;
    private javax.swing.JButton generateSnowFlake;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton pickTriangleColor;
    private javax.swing.JToggleButton showLine;
    private javax.swing.JCheckBoxMenuItem showLines;
    private snowflake.SnowFlakePanel snowFlakePanel;
    // End of variables declaration//GEN-END:variables
}
