/*
 * The MIT License
 *
 * Copyright 2019 lucamazza.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package snowpackage;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author lucamazza
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        snowFlakePanel.tf = trianglePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mousePositionLabel = new javax.swing.JLabel();
        snowFlakePanel = new snowpackage.SnowFlakePanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        pickTriangleColor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        resetCuts = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        savePoly = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jToolBar1 = new javax.swing.JToolBar();
        pointSize = new javax.swing.JSlider();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jToolBar3 = new javax.swing.JToolBar();
        trianglePanel = new snowpackage.TrianglePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        mousePositionLabel.setText("jLabel1");
        getContentPane().add(mousePositionLabel, java.awt.BorderLayout.PAGE_END);

        snowFlakePanel.setBackground(new java.awt.Color(255, 255, 255));
        snowFlakePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                snowFlakePanelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout snowFlakePanelLayout = new javax.swing.GroupLayout(snowFlakePanel);
        snowFlakePanel.setLayout(snowFlakePanelLayout);
        snowFlakePanelLayout.setHorizontalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        snowFlakePanelLayout.setVerticalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1284, Short.MAX_VALUE)
        );

        getContentPane().add(snowFlakePanel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jToolBar2.setRollover(true);
        jToolBar2.add(jSeparator4);

        pickTriangleColor.setText("Color");
        pickTriangleColor.setFocusable(false);
        pickTriangleColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pickTriangleColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pickTriangleColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickTriangleColorActionPerformed(evt);
            }
        });
        jToolBar2.add(pickTriangleColor);
        jToolBar2.add(jSeparator2);

        resetCuts.setText("Reset");
        resetCuts.setFocusable(false);
        resetCuts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetCuts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resetCuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCutsActionPerformed(evt);
            }
        });
        jToolBar2.add(resetCuts);
        jToolBar2.add(jSeparator5);

        savePoly.setText("Save polygon");
        savePoly.setFocusable(false);
        savePoly.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        savePoly.setMaximumSize(new java.awt.Dimension(70, 70));
        savePoly.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(savePoly);
        jToolBar2.add(jSeparator3);

        jToolBar1.setRollover(true);
        jToolBar2.add(jToolBar1);

        pointSize.setMaximum(50);
        pointSize.setMinimum(5);
        pointSize.setToolTipText("");
        pointSize.setValue(5);
        pointSize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pointSizeStateChanged(evt);
            }
        });
        jToolBar2.add(pointSize);
        jToolBar2.add(filler4);
        jToolBar2.add(filler2);
        jToolBar2.add(filler1);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jToolBar3.setRollover(true);

        trianglePanel.setBackground(new java.awt.Color(255, 255, 255));
        trianglePanel.setMaximumSize(new java.awt.Dimension(300, 500));
        trianglePanel.setMinimumSize(new java.awt.Dimension(300, 500));
        trianglePanel.setOpaque(false);
        trianglePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                trianglePanelMouseDragged(evt);
            }
        });
        trianglePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trianglePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout trianglePanelLayout = new javax.swing.GroupLayout(trianglePanel);
        trianglePanel.setLayout(trianglePanelLayout);
        trianglePanelLayout.setHorizontalGroup(
            trianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        trianglePanelLayout.setVerticalGroup(
            trianglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jToolBar3.add(trianglePanel);
        trianglePanel.getAccessibleContext().setAccessibleParent(snowFlakePanel);

        getContentPane().add(jToolBar3, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void snowFlakePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snowFlakePanelMouseMoved
        mousePositionLabel.setText(evt.getX() + " " + evt.getY());
    }//GEN-LAST:event_snowFlakePanelMouseMoved

    private void pointSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pointSizeStateChanged
        trianglePanel.RAD = pointSize.getValue();
        trianglePanel.repaint();
    }//GEN-LAST:event_pointSizeStateChanged

    private void resetCutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCutsActionPerformed
        trianglePanel.poly.reset();
        trianglePanel.points.clear();
        trianglePanel.repaint();
        snowFlakePanel.repaint();
    }//GEN-LAST:event_resetCutsActionPerformed

    private void pickTriangleColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickTriangleColorActionPerformed
        JColorChooser jcc = new JColorChooser();
        Color c = jcc.showDialog(null, "Select a color", Color.BLACK);
        snowFlakePanel.triangleColor = c;
        snowFlakePanel.repaint();
        trianglePanel.triangleColor = c;
        trianglePanel.repaint();
    }//GEN-LAST:event_pickTriangleColorActionPerformed

    private void trianglePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trianglePanelMouseClicked
        snowFlakePanel.repaint();
    }//GEN-LAST:event_trianglePanelMouseClicked

    private void trianglePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trianglePanelMouseDragged
        snowFlakePanel.repaint();
    }//GEN-LAST:event_trianglePanelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel mousePositionLabel;
    private javax.swing.JButton pickTriangleColor;
    private javax.swing.JSlider pointSize;
    private javax.swing.JButton resetCuts;
    private javax.swing.JButton savePoly;
    private snowpackage.SnowFlakePanel snowFlakePanel;
    private snowpackage.TrianglePanel trianglePanel;
    // End of variables declaration//GEN-END:variables
}
