/*
 * The MIT License
 *
 * Copyright 2019 Luca Mazza.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package snowpackage;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Polygon;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.Area;
import java.awt.geom.PathIterator;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author lucamazza
 */
public class SnowFlakePanel extends javax.swing.JPanel {
    
    /**
     * 
     */
    Point mousePosition;

    TrianglePanel tf;
    
    /**
     * 
     */
    boolean generated;
    
    /**
     * 
     */
    private Triangle t1;
    
    /**
     * 
     */
    private Point center;
    
    /**
     * 
     */
    Color triangleColor = Color.BLACK;
    
    /**
     * 
     */
    boolean newPolygon = false;
    
    /**
     *
     */
    int RAD = 5;
    
    /**
     * Creates new form TrianglePanel
     */
    public SnowFlakePanel() {
        this.mousePosition = new Point(0, 0);
        this.generated = true;
        
        initComponents();
    }
    
    /**
     *
     * @param g2d
     */
    @Override
    public void paintComponent(Graphics g){
        Graphics2D g2d = (Graphics2D) g;
        g2d.addRenderingHints(
                new RenderingHints(RenderingHints.KEY_ANTIALIASING,
                                   RenderingHints.VALUE_ANTIALIAS_ON));
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                             RenderingHints.VALUE_TEXT_ANTIALIAS_ON );
        this.t1 = new Triangle(this.getHeight(), this.getWidth(), this.generated);
        Area triangle = this.tf.triangle;
        g2d.setColor(this.triangleColor);
        this.center = new Point(this.tf.center.x, this.tf.center.y);
        for (int i = 6; i <= 36; i += 6) {
            g2d.fill(translateToCenter(rotateArea(flipArea(triangle), i*10)));
            g2d.fill(translateToCenter(rotateArea(triangle, i*10)));
        }
    }

    /**
     * 
     * @param origPoints
     * @return 
     */
    public Shape flipArea(Area origPoints) {
        AffineTransform ty2 = new AffineTransform();
        ty2.scale(-1, 1);
        AffineTransform ty3 = new AffineTransform();
        ty3.translate(-center.x * 2, 0);
        AffineTransform ty1 = new AffineTransform();
        ty1.concatenate(ty2);
        ty1.concatenate(ty3);
        return ty1.createTransformedShape(origPoints);
    }
    public Shape translateToCenter(Shape origPoints){
        AffineTransform ty1 = new AffineTransform();
        ty1.translate(-this.center.x, -this.center.y);
        AffineTransform ty2 = new AffineTransform();
        ty2.translate(this.getWidth()/2, this.getHeight()/2);
        AffineTransform ty = new AffineTransform();
        ty.concatenate(ty1);
        ty.concatenate(ty2);
        return ty.createTransformedShape(origPoints);
    }
    
    /**
     * 
     * @param origPoints
     * @param angle
     * @return 
     */
    public Shape rotateArea(Shape origPoints, double angle) {
        AffineTransform tx = new AffineTransform();
        tx.rotate(Math.toRadians(angle), this.center.x, this.center.y);
        return tx.createTransformedShape(origPoints);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
